global:
  scrape_interval: 15s  # 메트릭을 수집하는 주기
  evaluation_interval: 15s  # 룰 평가 주기

alerting:  #alerting.alertmanagers: Alertmanager의 주소를 설정합니다.
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']  #targets: Alertmanager가 실행 중인 호스트와 포트입니다.

rule_files: #rule_files: 경고 규칙 파일입니다.
  - "alert_rules.yml"
scrape_configs:  #scrape_configs: Prometheus가 메트릭을 수집할 엔드포인트 설정입니다.
  - job_name: 'CrawlerJob'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:9090']  # Prometheus HTTP 서버가 실행 중인 호스트 및 포트

  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets: [ 'pushgateway:9091' ]